server:
  port: 8080

spring:
  application:
    name: taxi-operation-system
  
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/taxi_operation_system?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    
  # Redis配置
  data:
    redis:
      host: localhost
      port: 6379
      password: 
      database: 0
      timeout: 10000ms
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

# MyBatis配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
  mapper-locations: classpath*:/mapper/**/*.xml

# JWT配置
jwt:
  secret: taxi-operation-system-secret-key-2024
  expiration: 86400000  # 24小时

# 文件上传路径配置
file:
  upload:
    path: uploads/

# 日志配置
logging:
  level:
    com.taxi: debug
    org.springframework.security: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"

# 高德地图API配置
amap:
  key: e78a59e4a55e6634055068f28955d282  # Web端API Key
  security-key: b8568193f0510e07a52f8d5f79fb0223  # 安全密钥
  base-url: https://restapi.amap.com/v3
  search:
    radius: 3000  # 搜索半径（米）
    page-size: 20  # 每页结果数

# 自定义配置 - 暂时注释
# taxi:
#   # 派单配置
#   dispatch:
#     auto-assign-radius: 5000  # 自动派单半径(米)
#     max-wait-time: 300        # 最大等待时间(秒)
#     min-driver-rating: 4.0    # 最低司机评分
#     max-cancel-rate: 0.1      # 最大取消率
#   
#   # 费用配置
#   fare:
#     base-fare: 10.00          # 基础起步价
#     per-km-fare: 2.50         # 每公里费用
#     service-fee-rate: 0.10    # 服务费比例 